-- ==============================================================================
-- MedScan AI - Migración Inicial de Base de Datos (Flyway V1)
-- ==============================================================================

-- 1. Tabla de Usuarios
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    push_token VARCHAR(255),
    role VARCHAR(50) NOT NULL DEFAULT 'USER'
);

-- 2. Tabla de Medicamentos
CREATE TABLE IF NOT EXISTS medicaments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    component_active VARCHAR(255),
    secondary_effect VARCHAR(1000),
    with_food BOOLEAN NOT NULL DEFAULT FALSE,
    dangerous_interactions VARCHAR(1000),
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_medicaments_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_medicaments_user_id ON medicaments(user_id);

-- 3. Tabla de Tratamientos
CREATE TABLE IF NOT EXISTS treatments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    medicament_id BIGINT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    interval_hours INT NOT NULL,
    dose_quantity INT NOT NULL,
    start_time TIME WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT fk_treatments_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_treatments_medicament FOREIGN KEY (medicament_id) REFERENCES medicaments(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_treatments_user_id ON treatments(user_id);
CREATE INDEX IF NOT EXISTS idx_treatments_medicament_id ON treatments(medicament_id);

-- 4. Tabla de Dosis
CREATE TABLE IF NOT EXISTS doses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    treatment_id BIGINT NOT NULL,
    scheduled_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    notified_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT fk_doses_treatment FOREIGN KEY (treatment_id) REFERENCES treatments(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_doses_treatment_id ON doses(treatment_id);
CREATE INDEX IF NOT EXISTS idx_doses_pending_scheduled ON doses(status, scheduled_at);
